const bodyParser = require('body-parser')
const fornecedores = require('./fornecedoresRoute.js')
const produtos = require('./produtosRoute.js')
const combos = require('./comboRoute.js')
const endereco = require('./enderecoRoute.js')
const usuario = require('./usuariosRoute.js')
const tipoProduto = require('./tipoProdutoRoute.js')
const pagamento = require('./pagamentoRoute.js')
const biritas = require('./biritasRoute.js')
const cardapio = require('./cardapioRoute.js')

module.exports = app => {
  app.use(bodyParser.json())
  app.use(fornecedores)
  app.use(produtos)
  app.use(combos)
  app.use(endereco)
  app.use(usuario)
  app.use(tipoProduto)
  app.use(pagamento)
  app.use(biritas)
  app.use(cardapio)
}
